### ISSUE TITLE
Tagcloud - Blacklist

### ISSUE THREAD

**Issue by marius300482** [chboehm/vufind-ida#2]
Wenn ich es richtig sehe, dann funktioniert die Blacklist, die für die Schlawortwolke existiert, noch nicht richtig. Bitte korrigieren.

**Comment by rproutermedia** [comment]
Kannst du das näher beschreiben? Welche Schlagworte sollten nicht auftauchen?

**Comment by b4seven** [comment]
habe die mit dem Dachverband abgestimmten Begriffe ergänzt, auf dem Dev-System funktioniert die Blacklist tadellos
