### ISSUE TITLE
Server-URL für QR-Codes fixen

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#20]
auf allen Systemen wird die interne IP verwendet => sollte aber die "url" aus der ida-config.ini sein

**Comment by b4seven** [comment]
Hallo @rproutermedia ,
ich brauche hier kurze Unterstützung bzw. einen Hinweis an welcher Stelle das zu fixen ist. 
Danke, Stefanie

**Comment by rproutermedia** [comment]
Ich habe den Webserver auf dem Host-System jetzt so konfiguriert, dass der Hostname korrekt an die Webserver der virtuellen Maschinen weitergereicht wird. Somit können die Instanzen ihre URLs richtig ermitteln und produzieren u.a. korrekte QR-Codes.
