### ISSUE TITLE
Serverumstellung

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#21]
Hallo @rproutermedia ,
von unserer Seite wäre für die Serverumstellung alles klar. Jetzt die Frage, muss an der Konfig der Hetzner-Server noch etwas geändert werden (prod.meta-katalog.eu => www.meta-katalog.eu)?
Danke, Stefanie

**Comment by rproutermedia** [comment]
Hallo,
ich stelle gerade noch die Weiterleitung vom Host-System zur prod VM ein, danach kann es von mir aus los gehen!

**Comment by rproutermedia** [comment]
Sobald der DNS umgeschaltet ist, wird das neue Live-System unter 
meta-katalog.eu 
www.meta-katalog.eu und 
prod.meta-katalog.eu 
erreichbar sein. Bei dieser Gelegenheit habe ich auch den Zugriffsschutz für das Live-System entfernt.

**Comment by b4seven** [comment]
Hallo @rproutermedia ,
vielen Dank. Marius hat eben auch den DNS-Eintrag umgestellt.
VG Stefanie
