### ISSUE TITLE
Ergebnisliste: Information ausblenden (Weitere Suche mit)

### ISSUE THREAD

**Issue by solonair** [chboehm/vufind-ida#27]
In der Ergebnisliste soll das folgende ausgeblendet werden:
![image](https://cloud.githubusercontent.com/assets/5205020/19249174/559926da-8f34-11e6-85eb-cd412656a729.png)

**Comment by marius300482** [comment]
Bei mir ist "Weitere Suche mit: ..." im mobilen Modus noch sichtbar.

![auswahl_054](https://cloud.githubusercontent.com/assets/7677191/19269369/828e3398-8fba-11e6-8273-d2f7d3570c41.png)

**Comment by ben-outermedia** [comment]
die Funktion ist jetzt online
