### ISSUE TITLE
Ergebnisse filtern: derzeitig Sprungmarke > Mit Bildlauf Anstatt Sprung

### ISSUE THREAD

**Issue by solonair** [chboehm/vufind-ida#28]
Ergebnisse filtern: derzeitig Sprungmarke > Mit Bildlauf Anstatt Sprung
![image](https://cloud.githubusercontent.com/assets/5205020/19249482/17001698-8f36-11e6-83be-0c21fb863ba9.png)

http://dev.meta-katalog.eu/Search/Results?lookfor=fu%C3%9Fball&limit=20&sort=relevance
In der mobilden Ansicht nach ganz unten scrollen

**Comment by gda-outermedia** [comment]
Smooth scrolling habe ich gestern Abend noch eingebaut

**Comment by marius300482** [comment]
funktioniert super und sieht sehr gut aus. Vielen Dank.
