### ISSUE TITLE
Vielleicht interessant?

### ISSUE THREAD

**Issue by marius300482** [chboehm/vufind-ida#3]
Die Funktion "Vielleicht interessant" zeigt auf dem derzeitigen Livesystem drei Einträge. In der Dev-Version nur 2 oder weniger. Auch hier gibt es ja eine Liste mit Dokumenten die Angezeigt werden können.

**Comment by rproutermedia** [comment]
Auf allen drei Instanzen sehe ich momentan drei Einträge.

**Comment by b4seven** [comment]
kann den Fehler momentan auch nicht nachvollziehen, auf allen Instanzen sind drei Einträge vorhanden
