### ISSUE TITLE
Piwik - Migration nach stats.ida-dachverband.de

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#4]
wohl erst sinnvoll mit Umzug der Domain auf prod.meta-katalog.eu
- [x] neue site auf stats.ida-dachverband.de anlegen
- [x] piwik-config in ida-config.ini ändern
- [x] alte daten mit hilfe von https://plugins.piwik.org/SiteMigration umziehen

**Comment by rproutermedia** [comment]
Dann ist natürlich die nächste Frage: wann wollen wir den Umzug durchführen?

**Comment by b4seven** [comment]
Umzug sobald das netzwerkproblem gelöst wurde...möglichst spätestens Anfang Juni

**Comment by b4seven** [comment]
erledigt
