### ISSUE TITLE
Ähnliche Einträge - teilweise keine Icons

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#6]
bei einigen Dokumenttypen (z.B. Film) werden im Bereich "ähnliche Einträge" keine Icons angezeigt
![aehnliche_eintraege](https://cloud.githubusercontent.com/assets/8090479/15243418/bfebcfa6-18fb-11e6-8b91-4ac837a8b1c2.png)

**Comment by rproutermedia** [comment]
Ich habe Icons für Filme und Zeitschriften zugewiesen und auf dev deployed. Bei weiteren Typen bitte melden!

**Comment by b4seven** [comment]
Danke, mehr sind mir im Moment nicht aufgefallen
