### ISSUE TITLE
Dev/Stage/Prod down

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#7]
alle VMs auf dem Hetzner-Server sind z.Zt. down (HTTP und SSH) und die VM-Oberfläche (siehe Link im Wiki) ist auch nicht erreichbar.
Bitte mal nachsehen.

Vielen Dank!

**Comment by outermedia-cbo** [comment]
War eines der Systeme nach "Start-Date: 2016-05-10  06:45:31" erreichbar?

**Comment by b4seven** [comment]
bin nicht 100% sicher, meine aber gestern gings...auf jeden Fall ist der Build von gestern nachmittag problemlos durchgelaufen

**Comment by outermedia-cbo** [comment]
Ursache nicht gefunden. Neustart des Servers und der virtuellen Maschinen stellt das Netzwerk wieder her.
Ob es einen Zusammenhang mit dem Kernelupdate gibt, konnte nicht verifiziert werden.
