### ISSUE TITLE
SCSS -> CSS ?

### ISSUE THREAD

**Issue by b4seven** [chboehm/vufind-ida#8]
Wie bzw. mit welchen Optionen kompiliert ihr das Scss?
Wenn ich Compass drüber laufen lassen, weicht das Ergebnis schon etwas vom bisherigen CSS ab.

Meine Optionen:
css_dir = "css"
sass_dir = "scss"
images_dir = "images"
javascripts_dir = "javascripts"
output_style = "compact"
line_comments = false

**Comment by rproutermedia** [comment]
Das SCSS ist auch mittlerweile ziemlich veraltet, da Marius meist nur das CSS angepasst hat. Das letzte Mal wurde das womöglich vor 8 Monaten kompiliert. Hier muss tatsächlich Arbeit hineingesteckt werden, um beides wieder auf denselben Stand zu bringen.

**Comment by b4seven** [comment]
danke für die Info, dann kümmere ich mich mal darum, die Änderungen wiederzufinden
